---
title: ""
---

$$\\[0.3cm]$$

## Publications
1. Seth Flaxman, Swapnil Mishra, Axel Gandy, H Juliette T Unwin, Thomas A Mellan, Helen Coupland, Charles Whittaker, Harrison Zhu, Tresnia Berah, Jeffrey W Eaton, **Mélodie Monod**, Azra C Ghani, Christl A Donnelly, Steven M Riley, Michaela AC Vollmer, Neil M Ferguson, Lucy C Okell, Samir Bhatt (2020). Estimating the effects of non-pharmaceutical interventions on COVID-19 in Europe. *Nature* **584**, 257–261 (2020). https://doi.org/10.1038/s41586-020-2405-7
2. H. Juliette T. Unwin, Swapnil Mishra, Valerie C. Bradley, Axel Gandy, Thomas A. Mellan, Helen Coupland, Jonathan Ish-Horowicz, Michaela A. C. Vollmer, Charles Whittaker, Sarah L. Filippi, Xiaoyue Xi, **Mélodie Monod**, Oliver Ratmann, Michael Hutchinson, Fabian Valka, Harrison Zhu, [...], Neil M. Ferguson, Steven Riley, Christl A. Donnelly, Samir Bhatt & Seth Flaxman et al. State-level tracking of COVID-19 in the United States. *Nat Commun* **11**, 6189 (2020). https://doi.org/10.1038/s41467-020-19652-6
3. **Mélodie Monod**, Alexandra Blenkinsop, Xiaoyue Xi, Daniel Hebert, Sivan Bershan, Valerie C Bradley, Yu Chen, Helen Coupland, Sarah Filippi, Jonathan Ish-Horowicz, Martin McManus, Thomas A Mellan,  Axel Gandy, Michael Hutchinson, H Juliette T Unwin, Michaela A. C. Vollmer, Sebastian Weber, Harrison Zhu, Anne Bezancon, Simon Tietze, Neil M Ferguson, Swapnil Mishra, Seth Flaxman, Samir Bhatt,  Oliver Ratmann. Age groups that sustain resurging COVID-19 epidemics in the United States. *medRxiv* (2020). doi: 10.1101/2020.09.18.20197376.

$$\\[0.3cm]$$

## Open source code
- Code for modelling estimated deaths and infections for COVID-19 used in [1], [2], [3] is available at https://github.com/ImperialCollegeLondon/covid19model
- Code for data scraping and processing age-stratified COVID-19 mortality used in [3] is available at https://github.com/ImperialCollegeLondon/US-covid19-agespecific-mortality-data

$$\\[0.3cm]$$

## Talks 
- StanCon 2020, August 13 2020.
- COVID-19 Dynamics & Evolution Webinar Series, University of California San Diego, October 19 2020.
- Banff International Research Station for Mathematical Innovation and Discovery, November 10 2020.